---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fabric-configure-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fabric-configure
subjects:
- kind: ServiceAccount
  name: fabric-configure
  namespace: uipath-infra
---
  
  
