apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: db-ca-cert
  namespace: mongodb
spec:
  secretName: db-ca-tls
  commonName: mongodb.svc.cluster.local
  usages:
    - server auth
    - client auth
  isCA: true
  issuerRef:
    name: selfsigned-issuer
